#FROM pytorch/pytorch:1.5-cuda10.1-cudnn7-devel
FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04
ENV DEBIAN_FRONTEND noninteractive
ENV PATH /opt/miniconda3/bin:$PATH
ENV CPLUS_INCLUDE_PATH /opt/miniconda3/include
RUN apt-get update
RUN apt-get install -y apt-file
RUN apt-get update
RUN apt-get install -y build-essential \
    checkinstall \
    cmake \
    pkg-config \
    yasm \
    git \
    gfortran \
    libjpeg8-dev libpng-dev \
    libtiff-dev \
    libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev \
    libxine2-dev libv4l-dev \
    liblmdb-dev libleveldb-dev libsnappy-dev \
    mesa-utils and libgl1-mesa-glx x11-apps eog \
    vim tmux curl
RUN ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so.7 /usr/local/cuda/lib64/libcudnn.so.7
RUN ln -s /usr/lib/x86_64-linux-gnu/libcudnn.so /usr/local/cuda/lib64/libcudnn.so

RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3
RUN conda update -y -n base -c defaults conda

RUN conda install -y numpy hdf5 cython numba matplotlib pandas scikit-learn scipy cudatoolkit

RUN conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

RUN conda update conda & conda update --all &&\
    apt-get update && apt-get install -y vim tmux htop wget &&\
    pip install transforms3d &&\
    wget -r -l1 -np -nd -nc http://cdaweb.gsfc.nasa.gov/pub/software/cdf/dist/latest-release/linux/ -A cdf*-dist-all.tar.gz &&\
    tar xf cdf*-dist-all.tar.gz -C ./ && \
    cd cdf*dist &&\
    apt install -y build-essential gfortran libncurses5-dev && \
    make OS=linux ENV=gnu CURSES=yes FORTRAN=no UCOPTIONS=-O2 SHARED=yes -j4 all &&\
    make install #no sudo
RUN pip install git+https://github.com/spacepy/spacepy.git

RUN echo 'export CDF_BASE=/cdf37_0-dist' >> ~/.bashrc &&\
    echo 'export CDF_INC=$CDF_BASE/include' >> ~/.bashrc &&\
    echo 'export CDF_LIB=$CDF_BASE/lib' >> ~/.bashrc &&\
    echo 'export CDF_BIN=$CDF_BASE/bin' >> ~/.bashrc &&\
    echo 'export LD_LIBRARY_PATH=$CDF_BASE/lib:$LD_LIBRARY_PATH' >> ~/.bashrc

ENV CDF_BASE /cdf37_0-dist
ENV CDF_INC /cdf37_0-dist/include
ENV CDF_LIB /cdf37_0-dist/lib
ENV CDF_BIN /cdf37_0-dist/bin

# install torchlight 1.0.0
#RUN git clone https://github.com/jutanke/DMGNN.git && cd DMGNN/torchlight && python setup.py install
#RUN conda install -y -c anaconda yaml
RUN pip install pyyaml
RUN echo "0.0.0" && pip install git+https://github.com/jutanke/mocap.git

ENV CUDA_VISIBLE_DEVICES 1

# -- dont add anything below!


